-- Add / update Texas softball programs (keeps all existing out-of-state schools)
-- Safe to re-run. Run npm run seed after applying.

ALTER TABLE schools ADD COLUMN IF NOT EXISTS abbreviation VARCHAR(20);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS aliases TEXT[] NOT NULL DEFAULT '{}';

INSERT INTO schools (school_name, abbreviation, aliases, division, state, athletics_url) VALUES
    ('University of Texas', 'UT', ARRAY['UT', 'Texas', 'Longhorns', 'UT Austin'], 'D1', 'TX', 'https://texassports.com'),
    ('Texas A&M University', 'A&M', ARRAY['A&M', 'TAMU', 'Texas A&M', 'Aggies'], 'D1', 'TX', 'https://12thman.com'),
    ('Baylor University', 'Baylor', ARRAY['Baylor', 'BAY', 'Bears'], 'D1', 'TX', 'https://baylorbears.com'),
    ('Odessa College', 'Odessa', ARRAY['Odessa', 'OC', 'Wranglers'], 'JUCO', 'TX', 'https://www.wranglersports.com'),
    ('Tyler Junior College', 'TJC', ARRAY['TJC', 'Tyler Junior', 'Apaches'], 'JUCO', 'TX', 'https://www.apacheathletics.com'),
    ('McLennan Community College', 'McLennan', ARRAY['McLennan', 'MCC', 'Highlanders'], 'JUCO', 'TX', 'https://www.mclennanathletics.com'),
    ('Grayson College', 'Grayson', ARRAY['Grayson', 'Vikings'], 'JUCO', 'TX', 'https://gcathletics.com'),
    ('University of Texas at Tyler', 'UT Tyler', ARRAY['UT Tyler', 'Patriots'], 'D2', 'TX', 'https://uttylerpatriots.com'),
    ('West Texas A&M University', 'WT', ARRAY['WT', 'West Texas A&M', 'Buffs', 'Buffaloes'], 'D2', 'TX', 'https://gobuffsgo.com'),
    ('Angelo State University', 'Angelo State', ARRAY['Angelo State', 'Angelo', 'Rams'], 'D2', 'TX', 'https://angelosports.com'),
    ('Texas Lutheran University', 'TLU', ARRAY['TLU', 'Texas Lutheran', 'Bulldogs'], 'D3', 'TX', 'https://tlubulldogs.com'),
    ('East Texas Baptist University', 'ETBU', ARRAY['ETBU', 'East Texas Baptist', 'Tigers'], 'D3', 'TX', 'https://www.etbuathletics.com'),
    ('Midland College', 'Midland', ARRAY['Midland', 'Lady Chaps', 'Chaps'], 'JUCO', 'TX', 'https://www.gochaps.com'),
    ('Temple College', 'Temple', ARRAY['Temple', 'Leopards'], 'JUCO', 'TX', 'https://templecollege.edu/athletics'),
    ('Weatherford College', 'Weatherford', ARRAY['Weatherford', 'Roos'], 'JUCO', 'TX', 'https://www.roos.com'),
    ('North Central Texas College', 'NCTC', ARRAY['NCTC', 'North Central Texas'], 'JUCO', 'TX', 'https://www.nctcathletics.com'),
    ('Vernon College', 'Vernon', ARRAY['Vernon', 'Chaparrals'], 'JUCO', 'TX', 'https://www.vernoncollege.edu/athletics'),
    ('Cisco College', 'Cisco', ARRAY['Cisco', 'Wranglers'], 'JUCO', 'TX', 'https://www.cisco.edu/athletics'),
    ('Howard College', 'Howard', ARRAY['Howard College', 'Hawks'], 'JUCO', 'TX', 'https://www.hchawk.com'),
    ('Western Texas College', 'WTC', ARRAY['WTC', 'Western Texas', 'Westerners'], 'JUCO', 'TX', 'https://www.wtc.edu/athletics'),
    ('Kilgore College', 'Kilgore', ARRAY['Kilgore', 'Rangers'], 'JUCO', 'TX', 'https://www.kilgore.edu/athletics'),
    ('Navarro College', 'Navarro', ARRAY['Navarro', 'Bulldogs'], 'JUCO', 'TX', 'https://navarrobulldogs.com'),
    ('Dallas College', 'Dallas College', ARRAY['Dallas College', 'Brookhaven', 'Mountain View'], 'JUCO', 'TX', 'https://www.dallascollege.edu/athletics'),
    ('Blinn College', 'Blinn', ARRAY['Blinn', 'Buccaneers', 'Bucs'], 'JUCO', 'TX', 'https://blinn.prestosports.com'),
    ('San Jacinto College', 'San Jac', ARRAY['San Jac', 'San Jacinto', 'Gators'], 'JUCO', 'TX', 'https://sanjac.prestosports.com'),
    ('Trinity Valley Community College', 'TVCC', ARRAY['TVCC', 'Trinity Valley', 'Cardinals'], 'JUCO', 'TX', 'https://tvcc.prestosports.com'),
    ('Paris Junior College', 'PJC', ARRAY['PJC', 'Paris JC', 'Dragons'], 'JUCO', 'TX', 'https://parisjc.prestosports.com'),
    ('Hill College', 'Hill', ARRAY['Hill College', 'Rebels'], 'JUCO', 'TX', 'https://hillcollege.prestosports.com'),
    ('Clarendon College', 'Clarendon', ARRAY['Clarendon', 'Bulldogs'], 'JUCO', 'TX', 'https://www.clarendoncollege.edu'),
    ('Frank Phillips College', 'Frank Phillips', ARRAY['Frank Phillips', 'FPC', 'Plainsmen'], 'JUCO', 'TX', 'https://frankphillips.prestosports.com'),
    ('El Paso Community College', 'EPCC', ARRAY['EPCC', 'El Paso CC', 'Tejanos'], 'JUCO', 'TX', 'https://epcc.prestosports.com'),
    ('Ranger College', 'Ranger', ARRAY['Ranger', 'Rangers'], 'JUCO', 'TX', 'https://rangercollege.prestosports.com'),
    ('Trinity University', 'Trinity', ARRAY['Trinity', 'Tigers'], 'D3', 'TX', 'https://www.trinity.edu/athletics'),
    ('Concordia University Texas', 'Concordia TX', ARRAY['Concordia Texas', 'CTX', 'Tornados'], 'D3', 'TX', 'https://athletics.concordia.edu'),
    ('University of Dallas', 'UDallas', ARRAY['UDallas', 'UD', 'Crusaders'], 'D3', 'TX', 'https://udallasathletics.com'),
    ('Austin College', 'Austin College', ARRAY['Austin College', 'Kangaroos'], 'D3', 'TX', 'https://www.austincollege.edu/athletics'),
    ('Hardin-Simmons University', 'HSU', ARRAY['HSU', 'Hardin-Simmons', 'Cowgirls'], 'D3', 'TX', 'https://hsusports.com'),
    ('Howard Payne University', 'HPU', ARRAY['HPU', 'Howard Payne', 'Yellow Jackets'], 'D3', 'TX', 'https://www.hputx.edu/athletics'),
    ('University of Mary Hardin-Baylor', 'UMHB', ARRAY['UMHB', 'Mary Hardin-Baylor', 'Crusaders'], 'D3', 'TX', 'https://www.umhb.edu/athletics'),
    ('Southwestern University', 'Southwestern', ARRAY['Southwestern', 'Pirates'], 'D3', 'TX', 'https://www.southwestern.edu/athletics'),
    ('Schreiner University', 'Schreiner', ARRAY['Schreiner', 'Mountaineers'], 'D3', 'TX', 'https://schreiner.edu/athletics'),
    ('LeTourneau University', 'LETU', ARRAY['LETU', 'LeTourneau', 'Yellowjackets'], 'D3', 'TX', 'https://www.letu.edu/athletics'),
    ('McMurry University', 'McMurry', ARRAY['McMurry', 'War Hawks'], 'D3', 'TX', 'https://mcmurrysports.com'),
    ('University of St. Thomas', 'UST', ARRAY['UST', 'St. Thomas', 'Celts'], 'D3', 'TX', 'https://www.stthom.edu/athletics'),
    ('University of Texas at Dallas', 'UTD', ARRAY['UTD', 'UT Dallas', 'Comets'], 'D3', 'TX', 'https://utdcomets.com'),
    ('Texas Woman''s University', 'TWU', ARRAY['TWU', 'Texas Woman''s', 'Pioneers'], 'D2', 'TX', 'https://twuathletics.com'),
    ('Texas A&M University-Kingsville', 'TAMUK', ARRAY['TAMUK', 'A&M Kingsville', 'Javelinas'], 'D2', 'TX', 'https://javelinaathletics.com'),
    ('Texas A&M International University', 'TAMIU', ARRAY['TAMIU', 'Dustdevils'], 'D2', 'TX', 'https://www.tamiu.edu/athletics'),
    ('University of Texas Permian Basin', 'UTPB', ARRAY['UTPB', 'Permian Basin', 'Falcons'], 'D2', 'TX', 'https://www.utpb.edu/athletics'),
    ('Lubbock Christian University', 'LCU', ARRAY['LCU', 'Lubbock Christian', 'Chaps'], 'D2', 'TX', 'https://lcuchaps.com'),
    ('St. Mary''s University', 'St. Mary''s', ARRAY['St. Mary''s', 'Rattlers'], 'D2', 'TX', 'https://www.rattlerathletics.com'),
    ('St. Edward''s University', 'St. Edward''s', ARRAY['St. Edward''s', 'Hilltoppers'], 'D2', 'TX', 'https://www.stedwards.edu/athletics'),
    ('Texas Tech University', 'TTU', ARRAY['TTU', 'Texas Tech', 'Red Raiders'], 'D1', 'TX', 'https://texastech.com'),
    ('University of Houston', 'Houston', ARRAY['Houston', 'UH', 'Cougars'], 'D1', 'TX', 'https://uhcougars.com'),
    ('Texas State University', 'Texas State', ARRAY['Texas State', 'TXST', 'Bobcats'], 'D1', 'TX', 'https://txst.com'),
    ('University of Texas at San Antonio', 'UTSA', ARRAY['UTSA', 'Roadrunners'], 'D1', 'TX', 'https://goutsa.com'),
    ('University of Texas at Arlington', 'UTA', ARRAY['UTA', 'UT Arlington', 'Mavericks'], 'D1', 'TX', 'https://utamavs.com'),
    ('University of Texas at El Paso', 'UTEP', ARRAY['UTEP', 'Miners'], 'D1', 'TX', 'https://utepminers.com'),
    ('Texas Southern University', 'TSU', ARRAY['TSU', 'Texas Southern', 'Tigers'], 'D1', 'TX', 'https://tsusports.com'),
    ('University of the Incarnate Word', 'UIW', ARRAY['UIW', 'Incarnate Word', 'Cardinals'], 'D1', 'TX', 'https://uiwcardinals.com'),
    ('Sam Houston State University', 'Sam Houston', ARRAY['Sam Houston', 'SHSU', 'Bearkats'], 'D1', 'TX', 'https://gobearkats.com'),
    ('University of North Texas', 'UNT', ARRAY['UNT', 'North Texas', 'Mean Green'], 'D1', 'TX', 'https://meangreensports.com'),
    ('TCU', 'TCU', ARRAY['TCU', 'Texas Christian', 'Horned Frogs'], 'D1', 'TX', 'https://gofrogs.com'),
    ('Rice University', 'Rice', ARRAY['Rice', 'Owls'], 'D1', 'TX', 'https://riceowls.com'),
    ('Abilene Christian University', 'ACU', ARRAY['ACU', 'Abilene Christian', 'Wildcats'], 'D1', 'TX', 'https://acusports.com')
ON CONFLICT (school_name) DO UPDATE SET
    abbreviation = EXCLUDED.abbreviation,
    aliases = EXCLUDED.aliases,
    division = EXCLUDED.division,
    state = EXCLUDED.state,
    athletics_url = EXCLUDED.athletics_url,
    updated_at = NOW();
